<<<<<<< HEAD
[testServer]
BROKER_HOST = 100.111.118.58
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = dmzHost
EXCHANGE = dmzExchange
QUEUE = list
;EXCHANGE_TYPE = ????
AUTO_DELETE = false

=======
[testServer]
BROKER_HOST = 100.111.118.58
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = dmzHost
EXCHANGE = dmzExchange
QUEUE = listGame
;EXCHANGE_TYPE = ????
AUTO_DELETE = true

>>>>>>> origin/deployment_scripting
