[deployHost]
;deployment ip
BROKER_HOST = 100.125.53.7
BROKER_PORT = 5672
USER = test
PASSWORD = test
;set up Virtual hosts (deployHost) then set exchange deployExchange 
;set up queues with deployHost - QA-Frontend, QA-Backend , Prod-Frontend...
;bind with exchange the queues
VHOST = deployHost
EXCHANGE = deployExchange
;each dev enviorment has a queue QA-BE, QA-FE, Pro-BE, Pro-FE change once in the right vm`
QUEUE = QA-BE
AUTO_DELETE = true

