[testServer]
BROKER_HOST = 100.100.107.42
BROKER_PORT = 5672
USER = test
PASSWORD = test
VHOST = testHost
EXCHANGE = testExchange
QUEUE = testQueue
;EXCHANGE_TYPE = ????
AUTO_DELETE = true
CONNECTION_TIMEOUT = 5
READ_TIMEOUT = 10
WRITE_TIMEOUT = 10 
